# Pull tomcat latest image from dockerhub 
From tomcat:latest@sha256:1a9ec4ac350eab68b3eaa9b9738cbbba652af6c1445f16ab9fd4864f6cb3d23d

# Maintainer
MAINTAINER "AR Shankar" 

# copy war file on to container 
COPY ./webapp.war /usr/local/tomcat/webapps