# Pull tomcat latest image from dockerhub 
From tomcat:latest@sha256:fd7f377c770f06b52e2b6cfee079fc744c77409862dc244d4631f49ba917c6d6

# Maintainer
MAINTAINER "AR Shankar" 

# copy war file on to container 
COPY ./webapp.war /usr/local/tomcat/webapps